name: New Initiative
description: A new initiative
labels:
  - "type: initiative"
body:
- type: textarea
  id: problem-statement
  attributes:
    label: Problem statement
    description: |
      Describe the problem being faced by one or more specific personas we care about. Use "As a ..." statements to capture the needs of the persona(s) involved.

- type: textarea
  id: proposed-solution
  attributes:
    label: Proposed solution
    description: |
      Describe how we intend to solve the problem, written in a way that is understandable to the persona(s) facing the problem.

- type: textarea
  id: proposed-implementation
  attributes:
    label: Proposed implementation
    description: |
      Provide a very broad description of how we propose to technically implement this solution.

- type: textarea
  id: existing-solutions
  attributes:
    label: Ecosystem fit and existing solutions
    description: |
      Describe how this fits into the broader open-source and health ecosystems. If similar solutions exist, explain how this builds on or differs from them.

- type: textarea
  id: when
  attributes:
    label: Timing and priority
    description: |
      Describe the priority of this initiative and any factors that affect when it should be worked on.

- type: textarea
  id: who-implements
  attributes:
    label: Team and endoresements
    description: |
      List the people involved in this work and others who support or are interested in it.
