name: "Validate issue"

on:
  issues:
    types: ["opened", "reopened", "edited", "labeled"]

jobs:
  validate-issue:
    name: "Validate issue"
    runs-on: "ubuntu-latest"
    permissions:
      issues: "write"
    steps:
    - uses: "actions/checkout@v6"
      with:
        fetch-depth: 0

    - name: "Install uv"
      uses: "astral-sh/setup-uv@v7"
      with:
        enable-cache: true

    - name: "Setup dependencies"
      run: |
        uv sync --no-dev

    - name: "Validate issue"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        uv run --no-sync \
          python -m \
            validator \
              ${{ github.event.issue.number }} \
              --post-report-as-comment
